name: Internal Test Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.VERSION_UPDATE_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Calculate New Version Code
        id: version
        run: |
          echo "$(python3 -c '
          import re

          def get_next_version():
              gradle_file = "app/build.gradle.kts"
              with open(gradle_file, "r") as f:
                  content = f.read()

              version_code_match = re.search(r"versionCode\s*=\s*(\d+)", content)
              if not version_code_match:
                  raise Exception("Version code not found")

              current_version = int(version_code_match.group(1))
              new_version = current_version + 1

              new_content = re.sub(
                  r"versionCode\s*=\s*\d+",
                  f"versionCode = {new_version}",
                  content
              )

              with open(gradle_file, "w") as f:
                  f.write(new_content)

              print(f"::set-output name=new_version_code::{new_version}")
              return new_version

          get_next_version()
          ')"

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Build AAB
        run: ./gradlew bundleRelease

      - name: Upload to Google Play Internal Test
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: studio.astroturf.thumbwrestling
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal

      - name: Commit Version Update
        if: success()
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add app/build.gradle.kts
          git commit -m "chore: Bump version code to ${{ steps.version.outputs.new_version_code }} after successful deploy [skip ci]"
          git push 